// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNASDAQEarningsCalendar(arg1:Array<string>):Promise<string>;

export function GetNSEBSEEarningsCalendar(arg1:Array<string>):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveFile():Promise<string>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
