// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNASDAQEarningsCalendar(arg1:Array<string>):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;
