name: Wails build

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          # - name: 'FinStats'
          #   platform:  'linux/amd64'
          #   os: 'ubuntu-latest'
          - name: 'FinStats'
            platform:  'windows/amd64'
            os: 'windows-latest'
          # - name: 'FinStats'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.20'