name: Build

on:
  release:
    types: [published]

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: FinStats, platform: linux/amd64, os: ubuntu-latest},
          {name: FinStats, platform: windows/amd64, os: windows-latest},
          {name: FinStats, platform: darwin/universal, os: macos-latest}
        ]

    runs-on: ${{ matrix.build.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: dAppServer/wails-build-action@v2.2
      with:
        build-name: ${{ matrix.build.name }}
        build-platform: ${{ matrix.build.platform }}
